name: 'Base Landing Page'
description: 'Cria o tipo de conteúdo Landing Page com as seções de parágrafos base do projeto.'
type: 'Content'
install:
  - paragraphs
  - entity_reference_revisions
  - media
  - taxonomy
  - webform
  - link
  - iconify_field
  - metatag
  - pathauto
  - token
  - responsive_image
  - image
  - options
  - text
  - node
config:
  import:
    paragraphs:
      - paragraphs.settings
    media:
      - media.settings
    taxonomy:
      - taxonomy.settings
    node:
      - node.settings

  actions:
    pathauto.pattern.landing_page:
      createIfNotExists:
        id: landing_page
        label: "Landing Page"
        type: "canonical_entities:node"
        pattern: "/[node:title]"
        weight: -10
        status: true
        relationships:
          "canonical_entities:node":
            bundles:
              - landing_page
            negate: false
