#!/bin/bash

# Load environment variables from .env
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi
CUSTOM_THEME_NAME=${CUSTOM_THEME_NAME:-front_theme}
THEME_FRAMEWORK=${THEME_FRAMEWORK:-tailwind}

cd web/themes/custom/$CUSTOM_THEME_NAME
npm run build
