name: 'Base Theme'
description: 'Scaffolds the custom frontend theme with Tailwind CSS'
type: 'Site'
recipes:
  - base_menus

install:
  - twig_tweak
  - base_theme

config:
  actions:
    system.theme:
      simple_config_update:
        default: front_theme # This value can be overwritten by the ddev theme-install command using .env
